name: Build and test

on:
  workflow_call:
    inputs:
      ref:
        description: The reference to build
        type: string
        required: true
      image:
        description: The name of the image to build
        type: string
        required: true
      context:
        description: The context used to build the image
        type: string
        required: true
      stage:
        description: The stage to build
        type: string
        required: false
      dockerfile:
        description: The path to the Dockerfile
        type: string
        required: false
      push:
        description: Whether to push the image to the registry
        type: boolean
        default: true
        required: false
    outputs:
      image-id:
        description: The ID of image that has been built
        value: ${{ jobs.build.outputs.image-id }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-id: ${{ steps.build.outputs.image-id }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - id: build
        name: Build and push
        uses: cern-sis/gh-workflows/.github/actions/docker-build@v6.5
        with:
          image: ${{ inputs.image }}
          context: ${{ inputs.context }}
          stage: ${{ inputs.stage }}
          dockerfile: ${{ inputs.dockerfile }}
          registry: registry.cern.ch
          push: ${{ inputs.push }}
          cache: false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
          username: ${{ inputs.push && secrets.HARBOR_USERNAME || '' }}
          password: ${{ inputs.push && secrets.HARBOR_PASSWORD || '' }}

      - name: Run tests
        run: |
          docker run --rm
            ${{ inputs.image }} \
            poetry run pytest tests/
