name: Push master

on:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    with:
      ref: ${{ github.sha }}
    secrets: inherit

  build_and_test:
    needs: pre-commit
    uses: ./.github/workflows/build_and_test.yml
    with:
      ref: ${{ github.sha }}
      image: cern-sis/inspire/classifier
      context: .
    secrets: inherit

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: send event
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v6.3.0
        with:
          event-type: update
          images: |
            cern-sis/inspire/classifier@${{ needs.build_and_test.outputs.image-id }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
