name: Push master

on:
  push:
    branches: [master]

jobs:
  test-python:
    uses: ./.github/workflows/test-python.yml

  bump_version:
    needs: [test-python]
    uses: ./.github/workflows/bump-and-publish.yml
    secrets: inherit
